id: IB48B5EB9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:12:20+00:00'
last_modified: '2022-06-08T03:43:10.074761+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13809
  title: མདོ་སྨད་དབལ་ཤུལ་གསེར་རྟའི་སྔོན་དང་ད་ལྟའི་དངོས་ཡོད་ཀྱི་ལོ་རྒྱུས་སྙིང་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4DAB:
      image_group_id: I1KG15782
      title: ''
      total_pages: 80
      order: 1
      base_file: 4DAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
