id: P005527
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13809
  title: མདོ་སྨད་དབལ་ཤུལ་གསེར་རྟའི་སྔོན་དང་ད་ལྟའི་དངོས་ཡོད་ཀྱི་ལོ་རྒྱུས་སྙིང་བསྡུས།
  author: ''
  volumes:
    f616284c66c048b493aa056c1b29420e:
      image_group_id: I1KG15782
      title: ''
      volume_number: 1
      total_pages: 80
